### ISSUE TITLE
HAMMER: Expect Fails for HammerDB Installation

### ISSUE THREAD

**Issue by dfhawthorne** [dfhawthorne/demos#3]
**Describe the bug**
The module, EXPECT, fails during the _Install HammerDB_, step.

**To Reproduce**
1. `cd demos/resource_manager_thruput`
2. `ansible-playbook -K install_hammerdb.yml`
3. See error

**Expected behavior**

**Screenshots**
The error is:
```
TASK [Install HammerDB] ********************************************************
fatal: [hammer.yaocm.id.au]: FAILED! => {"changed": false, "module_stderr": "Shared connection to hammer.yaocm.id.au closed.\r\n",
```
The formatted trace back is:
```
Traceback (most recent call last):
  File "/home/douglas/.ansible/tmp/ansible-tmp-1605317452.4483583-1826-185032744319898/AnsiballZ_expect.py", line 102, in <module>
    _ansiballz_main()
  File "/home/douglas/.ansible/tmp/ansible-tmp-1605317452.4483583-1826-185032744319898/AnsiballZ_expect.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/douglas/.ansible/tmp/ansible-tmp-1605317452.4483583-1826-185032744319898/AnsiballZ_expect.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.expect', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_expect_payload_8rcjyx51/ansible_expect_payload.zip/ansible/modules/expect.py", line 241, in <module>
  File "/tmp/ansible_expect_payload_8rcjyx51/ansible_expect_payload.zip/ansible/modules/expect.py", line 200, in main
  File "/usr/local/lib/python3.6/site-packages/pexpect/run.py", line 115, in run
    index = child.expect(patterns)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 342, in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
  File "/usr/local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 232, in compile_pattern_list
    compiled_pattern_list.append(re.compile(p, compile_flags))
  File "/usr/lib64/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib64/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib64/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range B-3 at position 58
```

**Comment by dfhawthorne** [comment]
The original patterns were too complicated. Have reduced the expected responses to single words.
